# Generated by Django 5.1.6 on 2025-09-26 16:43

import django.db.models.deletion
import rolodex.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRecordsLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Org2Org_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('relationship_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OrgContactRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('role', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='P2Org_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('relationship_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='P2P_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('relationship_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('role', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('orgName', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_edited_by', models.CharField(blank=True, max_length=250, null=True)),
                ('openRecordsLaw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rolodex.openrecordslaw')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Org2Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hierarchy', models.CharField(choices=[('parent', 'parent'), ('child', 'child'), ('none', 'none')], default='none', max_length=10)),
                ('from_ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_from_org', to='rolodex.org')),
                ('to_ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_to_org', to='rolodex.org')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org2org_relation', to='rolodex.org2org_type')),
            ],
        ),
        migrations.AddField(
            model_name='org',
            name='org_relations',
            field=models.ManyToManyField(blank=True, related_name='+', through='rolodex.Org2Org', to='rolodex.org'),
        ),
        migrations.CreateModel(
            name='P2Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('to_ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_to_org', to='rolodex.org')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2org_relation', to='rolodex.p2org_type')),
            ],
        ),
        migrations.CreateModel(
            name='P2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2p_relation', to='rolodex.p2p_type')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=250, null=True)),
                ('department', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=250, null=True)),
                ('birthdate', models.CharField(blank=True, max_length=50, null=True)),
                ('race', models.CharField(blank=True, choices=[('White', 'White'), ('Black', 'Black'), ('American Indian', 'American Indian'), ('Asian', 'Asian'), ('Native Hawaiian and other Pacific Islander', 'Native Hawaiian and other Pacific Islander'), ('Other', 'Other'), ('Two or more races', 'Two or more races')], max_length=250, null=True)),
                ('ethnicity', models.CharField(blank=True, choices=[('Hispanic', 'Hispanic'), ('Non-Hispanic', 'Non-Hispanic')], max_length=250, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_edited_by', models.CharField(blank=True, max_length=250, null=True)),
                ('org_relations', models.ManyToManyField(blank=True, related_name='people', through='rolodex.P2Org', to='rolodex.org')),
                ('p_relations', models.ManyToManyField(blank=True, related_name='+', through='rolodex.P2P', to='rolodex.person')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_role', to='rolodex.personrole')),
            ],
        ),
        migrations.AddField(
            model_name='p2p',
            name='from_ent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_from_p', to='rolodex.person'),
        ),
        migrations.AddField(
            model_name='p2p',
            name='to_ent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_to_p', to='rolodex.person'),
        ),
        migrations.AddField(
            model_name='p2org',
            name='from_ent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_from_p', to='rolodex.person'),
        ),
        migrations.CreateModel(
            name='Org2P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_from_org', to='rolodex.org')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org2p_relation', to='rolodex.p2org_type')),
                ('to_ent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_to_p', to='rolodex.person')),
            ],
        ),
        migrations.AddField(
            model_name='org',
            name='p_relations',
            field=models.ManyToManyField(blank=True, related_name='orgs', through='rolodex.Org2P', to='rolodex.person'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to=rolodex.models.upload_doc_directory)),
                ('link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_doc', to='rolodex.org')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_doc', to='rolodex.person')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'email'), ('phone', 'phone'), ('link', 'link'), ('address', 'address')], max_length=100)),
                ('contact', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_contact', to='rolodex.org')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rolodex.orgcontactrole')),
                ('person', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_contact', to='rolodex.person')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('datestamp', models.DateField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_log', to='rolodex.org')),
                ('person', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_log', to='rolodex.person')),
            ],
        ),
    ]
